server:
  port: 8080
spring:
  application:
    name: Dangi-Dongi
  datasource:
    url: jdbc:h2:mem:dangi-dongi
    driverClassName: org.h2.Driver
    username: dangi
    password: dongi
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: info
